/**
 * Bangladesh's Administrative Geography Data
 *
 * Data has been verified and corrected to reflect official administrative boundaries as of 2024,
 *
 * Divisions: 8
 * Districts: 64
 * Upazilas: 495
 */
const bdGeoData = [
  {
    division: "Barishal",
    districts: [
      {
        district: "Barishal",
        upazilas: [
          "Agailjhara",
          "Babuganj",
          "Bakerganj",
          "Banaripara",
          "Gournadi",
          "Hizla",
          "Barishal Sadar",
          "Mehendiganj",
          "Muladi",
          "Wazirpur",
        ],
      },
      {
        district: "Barguna",
        upazilas: [
          "Amtali",
          "Bamna",
          "Barguna Sadar",
          "Betagi",
          "Patharghata",
          "Taltali",
        ],
      },
      {
        district: "Bhola",
        upazilas: [
          "Bhola Sadar",
          "Burhanuddin",
          "Char Fasson",
          "Daulatkhan",
          "Lalmohan",
          "Manpura",
          "Tazumuddin",
        ],
      },
      {
        district: "Jhalokati",
        upazilas: ["Jhalokati Sadar", "Kathalia", "Nalchity", "Rajapur"],
      },
      {
        district: "Patuakhali",
        upazilas: [
          "Bauphal",
          "Dashmina",
          "Dumki",
          "Galachipa",
          "Kalapara",
          "Mirzaganj",
          "Patuakhali Sadar",
          "Rangabali",
        ],
      },
      {
        district: "Pirojpur",
        upazilas: [
          "Bhandaria",
          "Indurkani",
          "Kaukhali",
          "Mathbaria",
          "Nazirpur",
          "Nesarabad (Swarupkati)",
          "Pirojpur Sadar",
        ],
      },
    ],
  },
  {
    division: "Chattogram",
    districts: [
      {
        district: "Bandarban",
        upazilas: [
          "Ali Kadam",
          "Bandarban Sadar",
          "Lama",
          "Naikhongchhari",
          "Rowangchhari",
          "Ruma",
          "Thanchi",
        ],
      },
      {
        district: "Brahmanbaria",
        upazilas: [
          "Akhaura",
          "Ashuganj",
          "Bancharampur",
          "Bijoynagar",
          "Brahmanbaria Sadar",
          "Kasba",
          "Nabinagar",
          "Nasirnagar",
          "Sarail",
        ],
      },
      {
        district: "Chandpur",
        upazilas: [
          "Chandpur Sadar",
          "Faridganj",
          "Haimchar",
          "Hajiganj",
          "Kachua",
          "Matlab Dakshin",
          "Matlab Uttar",
          "Shahrasti",
        ],
      },
      {
        district: "Chattogram",
        upazilas: [
          "Anwara",
          "Banshkhali",
          "Boalkhali",
          "Chandanaish",
          "Fatikchhari",
          "Hathazari",
          "Karnaphuli",
          "Lohagara",
          "Mirsharai",
          "Patiya",
          "Rangunia",
          "Raozan",
          "Sandwip",
          "Satkania",
          "Sitakunda",
        ],
      },
      {
        district: "Cumilla",
        upazilas: [
          "Barura",
          "Brahmanpara",
          "Burichang",
          "Chandina",
          "Chauddagram",
          "Cumilla Adarsha Sadar",
          "Cumilla Sadar Dakshin",
          "Daudkandi",
          "Debidwar",
          "Homna",
          "Laksam",
          "Lalmai",
          "Meghna",
          "Monohargonj",
          "Muradnagar",
          "Nangalkot",
          "Titas",
        ],
      },
      {
        district: "Cox's Bazar",
        upazilas: [
          "Chakaria",
          "Cox's Bazar Sadar",
          "Eidgaon", // Added
          "Kutubdia",
          "Maheshkhali",
          "Pekua",
          "Ramu",
          "Teknaf",
          "Ukhia",
        ],
      },
      {
        district: "Feni",
        upazilas: [
          "Chhagalnaiya",
          "Daganbhuiyan",
          "Feni Sadar",
          "Fulgazi",
          "Parshuram",
          "Sonagazi",
        ],
      },
      {
        district: "Khagrachhari",
        upazilas: [
          "Dighinala",
          "Guimara",
          "Khagrachhari Sadar",
          "Lakshmichhari",
          "Mahalchhari",
          "Manikchhari",
          "Matiranga",
          "Panchhari",
          "Ramgarh",
        ],
      },
      {
        district: "Lakshmipur",
        upazilas: [
          "Kamalnagar",
          "Lakshmipur Sadar",
          "Raipur",
          "Ramganj",
          "Ramgati",
        ],
      },
      {
        district: "Noakhali",
        upazilas: [
          "Begumganj",
          "Chatkhil",
          "Companiganj",
          "Hatiya",
          "Kabirhat",
          "Noakhali Sadar",
          "Senbagh",
          "Sonaimuri",
          "Subarnachar",
        ],
      },
      {
        district: "Rangamati",
        upazilas: [
          "Bagaichhari",
          "Barkal",
          "Belaichhari",
          "Juraichhari",
          "Kaptai",
          "Kawkhali (Betbunia)",
          "Langadu",
          "Naniarchar",
          "Rajasthali",
          "Rangamati Sadar",
        ],
      },
    ],
  },
  {
    division: "Dhaka",
    districts: [
      {
        district: "Dhaka",
        upazilas: ["Dhamrai", "Dohar", "Keraniganj", "Nawabganj", "Savar"],
      },
      {
        district: "Faridpur",
        upazilas: [
          "Alfadanga",
          "Bhanga",
          "Boalmari",
          "Char Bhadrasan",
          "Faridpur Sadar",
          "Madhukhali",
          "Nagarkanda",
          "Sadarpur",
          "Saltha",
        ],
      },
      {
        district: "Gazipur",
        upazilas: [
          "Gazipur Sadar",
          "Kaliakair",
          "Kaliganj",
          "Kapasia",
          "Sreepur",
        ],
      },
      {
        district: "Gopalganj",
        upazilas: [
          "Gopalganj Sadar",
          "Kashiani",
          "Kotalipara",
          "Muksudpur",
          "Tungipara",
        ],
      },
      {
        district: "Kishoreganj",
        upazilas: [
          "Astagram",
          "Bajitpur",
          "Bhairab",
          "Hossainpur",
          "Itna",
          "Karimganj",
          "Katiadi",
          "Kishoreganj Sadar",
          "Kuliarchar",
          "Mithamain",
          "Nikli",
          "Pakundia",
          "Tarail",
        ],
      },
      {
        district: "Madaripur",
        upazilas: [
          "Dasar", // Added
          "Kalkini",
          "Madaripur Sadar",
          "Rajoir",
          "Shibchar",
        ],
      },
      {
        district: "Manikganj",
        upazilas: [
          "Daulatpur",
          "Ghior",
          "Harirampur",
          "Manikganj Sadar",
          "Saturia",
          "Shibalaya",
          "Singair",
        ],
      },
      {
        district: "Munshiganj",
        upazilas: [
          "Gazaria",
          "Lohajang",
          "Munshiganj Sadar",
          "Sirajdikhan",
          "Sreenagar",
          "Tongibari",
        ],
      },
      {
        district: "Narayanganj",
        upazilas: [
          "Araihazar",
          "Bandar",
          "Narayanganj Sadar",
          "Rupganj",
          "Sonargaon",
        ],
      },
      {
        district: "Narsingdi",
        upazilas: [
          "Belabo",
          "Monohardi",
          "Narsingdi Sadar",
          "Palash",
          "Raipura",
          "Shibpur",
        ],
      },
      {
        district: "Rajbari",
        upazilas: [
          "Baliakandi",
          "Goalandaghat",
          "Kalukhali",
          "Pangsha",
          "Rajbari Sadar",
        ],
      },
      {
        district: "Shariatpur",
        upazilas: [
          "Bhedarganj",
          "Damudya",
          "Gosairhat",
          "Naria",
          "Shariatpur Sadar",
          "Zanjira",
        ],
      },
      {
        district: "Tangail",
        upazilas: [
          "Basail",
          "Bhuapur",
          "Delduar",
          "Dhanbari",
          "Ghatail",
          "Gopalpur",
          "Kalihati",
          "Madhupur",
          "Mirzapur",
          "Nagarpur",
          "Sakhipur",
          "Tangail Sadar",
        ],
      },
    ],
  },
  {
    division: "Khulna",
    districts: [
      {
        district: "Bagerhat",
        upazilas: [
          "Bagerhat Sadar",
          "Chitalmari",
          "Fakirhat",
          "Kachua",
          "Mollahat",
          "Mongla",
          "Morrelganj",
          "Rampal",
          "Sarankhola",
        ],
      },
      {
        district: "Chuadanga",
        upazilas: ["Alamdanga", "Chuadanga Sadar", "Damurhuda", "Jibannagar"],
      },
      {
        district: "Jashore",
        upazilas: [
          "Abhaynagar",
          "Bagherpara",
          "Chaugachha",
          "Jhikargachha",
          "Jashore Sadar",
          "Keshabpur",
          "Manirampur",
          "Sharsha",
        ],
      },
      {
        district: "Jhenaidah",
        upazilas: [
          "Harinakundu",
          "Jhenaidah Sadar",
          "Kaliganj",
          "Kotchandpur",
          "Maheshpur",
          "Shailkupa",
        ],
      },
      {
        district: "Khulna",
        upazilas: [
          "Batiaghata",
          "Dacope",
          "Dighalia",
          "Dumuria",
          "Koyra",
          "Paikgachha",
          "Phultala",
          "Rupsa",
          "Terokhada",
        ],
      },
      {
        district: "Kushtia",
        upazilas: [
          "Bheramara",
          "Daulatpur",
          "Khoksa",
          "Kumarkhali",
          "Kushtia Sadar",
          "Mirpur",
        ],
      },
      {
        district: "Magura",
        upazilas: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
      },
      {
        district: "Meherpur",
        upazilas: ["Gangni", "Meherpur Sadar", "Mujibnagar"],
      },
      {
        district: "Narail",
        upazilas: ["Kalia", "Lohagara", "Narail Sadar"],
      },
      {
        district: "Satkhira",
        upazilas: [
          "Assasuni",
          "Debhata",
          "Kalaroa",
          "Kaliganj",
          "Satkhira Sadar",
          "Shyamnagar",
          "Tala",
        ],
      },
    ],
  },
  {
    division: "Mymensingh",
    districts: [
      {
        district: "Jamalpur",
        upazilas: [
          "Bakshiganj",
          "Dewanganj",
          "Islampur",
          "Jamalpur Sadar",
          "Madarganj",
          "Melandah",
          "Sarishabari",
        ],
      },
      {
        district: "Mymensingh",
        upazilas: [
          "Bhaluka",
          "Dhobaura",
          "Fulbaria",
          "Gaffargaon",
          "Gauripur",
          "Haluaghat",
          "Ishwarganj",
          "Mymensingh Sadar",
          "Muktagachha",
          "Nandail",
          "Phulpur",
          "Tarakanda",
          "Trishal",
        ],
      },
      {
        district: "Netrokona",
        upazilas: [
          "Atpara",
          "Barhatta",
          "Durgapur",
          "Khaliajuri",
          "Kalmakanda",
          "Kendua",
          "Madan",
          "Mohanganj",
          "Netrokona Sadar",
          "Purbadhala",
        ],
      },
      {
        district: "Sherpur",
        upazilas: [
          "Jhenaigati",
          "Nakla",
          "Nalitabari",
          "Sherpur Sadar",
          "Sreebardi",
        ],
      },
    ],
  },
  {
    division: "Rajshahi",
    districts: [
      {
        district: "Bogura",
        upazilas: [
          "Adamdighi",
          "Bogura Sadar",
          "Dhunat",
          "Dhupchanchia",
          "Gabtali",
          "Kahaloo",
          "Nandigram",
          "Sariakandi",
          "Shajahanpur",
          "Sherpur",
          "Shibganj",
          "Sonatala",
        ],
      },
      {
        district: "Chapainawabganj",
        upazilas: [
          "Bholahat",
          "Gomastapur",
          "Nachole",
          "Chapainawabganj Sadar",
          "Shibganj",
        ],
      },
      {
        district: "Joypurhat",
        upazilas: [
          "Akkelpur",
          "Joypurhat Sadar",
          "Kalai",
          "Khetlal",
          "Panchbibi",
        ],
      },
      {
        district: "Naogaon",
        upazilas: [
          "Atrai",
          "Badalgachhi",
          "Dhamoirhat",
          "Manda",
          "Mahadevpur",
          "Naogaon Sadar",
          "Niamatpur",
          "Patnitala",
          "Porsha",
          "Raninagar",
          "Sapahar",
        ],
      },
      {
        district: "Natore",
        upazilas: [
          "Bagatipara",
          "Baraigram",
          "Gurudaspur",
          "Lalpur",
          "Naldanga",
          "Natore Sadar",
          "Singra",
        ],
      },
      {
        district: "Pabna",
        upazilas: [
          "Atghoria",
          "Bera",
          "Bhangura",
          "Chatmohar",
          "Faridpur",
          "Ishwardi",
          "Pabna Sadar",
          "Santhia",
          "Sujanagar",
        ],
      },
      {
        district: "Rajshahi",
        upazilas: [
          "Bagha",
          "Bagmara",
          "Charghat",
          "Durgapur",
          "Godagari",
          "Mohanpur",
          "Paba",
          "Puthia",
          "Tanore",
        ],
      },
      {
        district: "Sirajganj",
        upazilas: [
          "Belkuchi",
          "Chauhali",
          "Kamarkhanda",
          "Kazipur",
          "Raiganj",
          "Shahjadpur",
          "Sirajganj Sadar",
          "Tarash",
          "Ullahpara",
        ],
      },
    ],
  },
  {
    division: "Rangpur",
    districts: [
      {
        district: "Dinajpur",
        upazilas: [
          "Birampur",
          "Birganj",
          "Birol",
          "Bochaganj",
          "Chirirbandar",
          "Dinajpur Sadar",
          "Fulbari",
          "Ghoraghat",
          "Hakimpur",
          "Kaharole",
          "Khansama",
          "Nawabganj",
          "Parbatipur",
        ],
      },
      {
        district: "Gaibandha",
        upazilas: [
          "Fulchhari",
          "Gaibandha Sadar",
          "Gobindaganj",
          "Palashbari",
          "Sadullapur",
          "Saghata",
          "Sundarganj",
        ],
      },
      {
        district: "Kurigram",
        upazilas: [
          "Bhurungamari",
          "Char Rajibpur",
          "Chilmari",
          "Kurigram Sadar",
          "Nageshwari",
          "Phulbari",
          "Rajarhat",
          "Raumari",
          "Ulipur",
        ],
      },
      {
        district: "Lalmonirhat",
        upazilas: [
          "Aditmari",
          "Hatibandha",
          "Kaliganj",
          "Lalmonirhat Sadar",
          "Patgram",
        ],
      },
      {
        district: "Nilphamari",
        upazilas: [
          "Dimla",
          "Domar",
          "Jaldhaka",
          "Kishoreganj",
          "Nilphamari Sadar",
          "Saidpur",
        ],
      },
      {
        district: "Panchagarh",
        upazilas: ["Atwari", "Boda", "Debiganj", "Panchagarh Sadar", "Tetulia"],
      },
      {
        district: "Rangpur",
        upazilas: [
          "Badarganj",
          "Gangachara",
          "Kaunia",
          "Mithapukur",
          "Pirgachha",
          "Pirganj",
          "Rangpur Sadar",
          "Taraganj",
        ],
      },
      {
        district: "Thakurgaon",
        upazilas: [
          "Baliadangi",
          "Haripur",
          "Pirganj",
          "Ranisankail",
          "Thakurgaon Sadar",
        ],
      },
    ],
  },
  {
    division: "Sylhet",
    districts: [
      {
        district: "Habiganj",
        upazilas: [
          "Ajmiriganj",
          "Bahubal",
          "Baniyachong",
          "Chunarughat",
          "Habiganj Sadar",
          "Lakhai",
          "Madhabpur",
          "Nabiganj",
          "Shaistaganj",
        ],
      },
      {
        district: "Moulvibazar",
        upazilas: [
          "Barlekha",
          "Juri",
          "Kamalganj",
          "Kulaura",
          "Moulvibazar Sadar",
          "Rajnagar",
          "Sreemangal",
        ],
      },
      {
        district: "Sunamganj",
        upazilas: [
          "Bishwamvarpur",
          "Chhatak",
          "Derai",
          "Dharamapasha",
          "Dowarabazar",
          "Jagannathpur",
          "Jamalganj",
          "Madhyanagar", // Added
          "Shalla",
          "Shantiganj", // Renamed from Dakshin Sunamganj
          "Sunamganj Sadar",
          "Tahirpur",
        ],
      },
      {
        district: "Sylhet",
        upazilas: [
          "Balaganj",
          "Beanibazar",
          "Bishwanath",
          "Companiganj",
          "Dakshin Surma",
          "Fenchuganj",
          "Golapganj",
          "Gowainghat",
          "Jaintiapur",
          "Kanaighat",
          "Osmani Nagar",
          "Sylhet Sadar",
          "Zakiganj",
        ],
      },
    ],
  },
];

export default bdGeoData;
